### ISSUE TITLE
orbacle running for 26 hours now..

### ISSUE THREAD

**Issue by mathieujobin** [swistak35/orbacle#6]
Large code base maybe. 100,000 LOC. Old rails 4.2 app

Orbacle is indexing for more than a day..

Is that normal?

I just notice last issue is a year old.

Is it a recommended language server to use?

**Comment by mathieujobin** [comment]
unmaintained, I get it. thank you

**Comment by swistak35** [comment]
@mathieujobin sorry for lack of answer, yes, I don't have the time for the project right now :)
